namespace Necromancy.Server.Systems.Item
{
    public enum ItemType
    {
        NONE = 0,
        TRUMP = 1,
        DAGGER = 2,
        SWORD_1H = 4,
        RAPIER = 3,
        SWORD_2H = 5,
        KATANA_1H = 6,
        KATANA_2H = 7,
        AXE_1H = 8,
        AXE_2H = 9,
        CLUB_1H = 11,
        CLUB_2H = 12,
        WAND_1H = 13,
        WAND_2H = 14,
        SPEAR = 10,
        BOW = 15,
        CROSSBOW = 16,
        GUN = 17,
        INSTRUMENT = 18,
        SHIELD_SMALL = 19,
        SHIELD_MEDIUM = 20,
        SHIELD_LARGE = 21,
        ARROW = 22,
        BOLT = 23,
        BULLET = 24,
        PROTECTOR = 25, //PROTCT
        ACCESSORY = 26, //ACCRY
        HELMET = 27,
        HAT = 28,
        HOOD = 29,
        ARMOR_TOPS = 30, //ARMOR
        ARMOR_BOTTOMS = 31, //GREAVES
        CLOTHES_TOPS = 32, //TOP
        CLOTHES_BOTTOMS = 33,
        COAT = 34,
        GLOVES = 35,
        GAUNTLETS = 36,
        BRACLET = 37,
        SABATONS = 38, //S.SHOE
        SHOES = 39, // SHOES
        CLOAK = 40, // 
        RING = 41,
        EARRING = 42,
        NECKLACE = 43, //NCKLCE
        BELT = 44,
        DRUG = 45, //MEDICINE
        SKILLCHIP =46, //SKLCHP
        BAG = 47,
        LOSTSOUL = 48, //LSTSOL
        EVENT = 49,
        FORGESTONE = 50, //FG_STN
        TALKRING_MAKEKIT = 51, //TOKRNG
        MASTER_TALKRING = 52, //TOKRING
        TALKRING = 53, //TOKRNG
        FORGEGUARDSTONE = 54, //FG_GRD
        GEM = 55, //GEM
        GEM_PIECE = 56, //GEM
        GEM_SYNTHESIS = 57, //GEM
        MAP_FRAGMENT = 58, //MAP PC
        OTHERS = 59, //OTHER
        AVATAR = 60,
        ALLCHT = 61,
        BUFF = 62,
        LEATHER =39, //L.SHOES
        FORGETICKET = 64, //FG_TKT
        FORGE_SP_SUPPORT = 65, //特殊鍛錬万能素材
        MATERIAL = 99, //JP ONLY
        WHOLECHAT = ALLCHT,
    }
}
