namespace Necromancy.Server.Model
{
    public enum ItemType
    {
        NONE = 0,
        TRUMP = 1,
        DAGGER = 2,
        RAPIER = 3,
        SWORD_1H = 4,
        SWORD_2H = 5,
        KATANA_1H = 6,
        KATANA_2H = 7,
        AXE_1H = 8,
        AXE_2H = 9,
        SPEAR = 10,
        CLUB_1H = 11,
        CLUB_2H = 12,
        WAND_1H = 13,
        WAND_2H = 14,
        BOW = 15,
        CROSSBOW = 16,
        GUN = 17,
        INSTRUMENT = 18,
        DOUBLE_EDGED = 19,
        SHIELD_SMALL = 20,
        SHIELD_MEDIUM = 21,
        SHIELD_LARGE = 22,
        ARROW = 23,
        BOLT = 24,
        BULLET = 25,
        PROTECTOR = 26, //PROTCT
        ACCESSORY = 27, //ACCRY
        HELMET = 28,
        HAT = 29,
        HOOD = 30,
        ARMOR_TOPS = 31, //ARMOR
        ARMOR_BOTTOMS = 32, //GREAVES
        CLOTHES_TOPS = 33, //TOP
        CLOTHES_BOTTOMS = 34,
        COAT = 35,
        GLOVES = 36,
        GAUNTLETS = 37,
        BRACLET = 38,
        SABATONS = 39, //S.SHOE
        LEATHER = 40, //L.SHOE
        SHOES = 40, // SHOES
        CLOAK = 41, // 
        RING = 42,
        EARRING = 43,
        NECKLACE = 44, //NCKLCE
        BELT = 45,
        DRUG = 46, //MEDICINE
        SKILLCHIP =47, //SKLCHP
        BAG = 48,
        LOSTSOUL = 49, //LSTSOL
        EVENT = 50,
        FORGESTONE = 51, //FG_STN
        TALKRING_MAKEKIT = 52, //TOKRNG
        MASTER_TALKRING = 53, //TOKRING
        TALKRING = 54, //TOKRNG
        FORGEGUARDSTONE = 55, //FG_GRD
        GEM = 56, //GEM
        GEM_PIECE = 57, //GEM
        GEM_SYNTHESIS = 58, //GEM
        MAP_FRAGMENT = 59, //MAP PC
        OTHERS = 60, //OTHER
        AVATAR = 61,
        ALLCHT = 62,
        BUFF = 63,
        FORGETICKET = 64, //FG_TKT
        FORGE_SP_SUPPORT = 65, //特殊鍛錬万能素材
        FORGE_GEM_SUPPORT = 66, //L.SHOES
        BUFF_FOOD = 67, //L.SHOES
        ARRANGE_TICKET = 68, //L.SHOES
        MATERIAL = 99, //JP ONLY
        WHOLECHAT = ALLCHT,
    }
}
