namespace Necromancy.Server.Model
{
    public enum ItemType
    {
        NONE = 0,
        TRUMP = 1,
        DAGGER = 2,
        SWORD_1H = 4,
        RAPIER = 3,
        SWORD_2H = 5,
        KATANA_1H = 6,
        KATANA_2H = 7,
        AXE_1H = 8,
        AXE_2H = 9,
        CLUB_1H = 11,
        CLUB_2H = 12,
        WAND_1H = 13,
        WAND_2H = 14,
        SPEAR = 10,
        BOW = 15,
        CROSSBOW = 16,
        GUN = 17,
        INSTRUMENT = 18,
        DOUBLE_EDGED = 19,
        SHIELD_SMALL = 20,
        SHIELD_MEDIUM = 21,
        SHIELD_LARGE = 22,
        ARROW = 23,
        BOLT = 24,
        BULLET = 25,
        PROTECTOR = 26, //PROTCT
        ACCESSORY = 27, //ACCRY
        HELMET = 28,
        HAT = 29,
        HOOD = 30,
        ARMOR_TOPS = 31, //ARMOR
        ARMOR_BOTTOMS = 32, //GREAVES
        CLOTHES_TOPS = 33, //TOP
        CLOTHES_BOTTOMS = 34,
        COAT = 35,
        GLOVES = 36,
        GAUNTLETS = 37,
        BRACLET = 38,
        SABATONS = 39, //S.SHOE
        SHOES = 41, // SHOES
        CLOAK = 42, // 
        RING = 43,
        EARRING = 44,
        NECKLACE = 45, //NCKLCE
        BELT = 46,
        DRUG = 47, //MEDICINE
        SKILLCHIP =48, //SKLCHP
        BAG = 49,
        LOSTSOUL = 50, //LSTSOL
        EVENT = 74,
        FORGESTONE = 51, //FG_STN
        TALKRING_MAKEKIT = 52, //TOKRNG
        MASTER_TALKRING = 53, //TOKRING
        TALKRING = 54, //TOKRNG
        FORGEGUARDSTONE = 55, //FG_GRD
        FORGE_PARAMETER_SUPPORT = 56,
        GEM = 57, //GEM
        GEM_PIECE = 58, //GEM
        GEM_SPALL = 59,
        GEM_SYNTHESIS = 60, //GEM
        MAP_FRAGMENT = 61, //MAP PC
        OTHERS = 62, //OTHER
        AVATAR = 63,
        ALLCHT = 64,
        BUFF = 65,
        LEATHER =40, //L.SHOES
        FORGETICKET = 66, //FG_TKT
        FORGE_SP_SUPPORT = 67, //特殊鍛錬万能素材
        FORGE_GEM_SUPPORT = 68,
        BUFF_FOOD = 69,
        ARRANGE_TICKET = 70,
        PARTNER_CARD = 71,
        PARTNER_NURTURE_FOOD = 72,
        PARTNER_NURTURE_PLAY = 73,
        SEASON_EVENT = 74,
        TREASURE_KYE = 75,
        DEPUS = 76,
        SKILL_BOOK = 77,
        JOB_CHANGE = 78,
        CAMP = 79,
        TOOL = 80,
        COLLECTION = 81,
        MATERIAL = 82, //JP ONLY
        SPHERE = 83,
        CAMPAIGN = 84,
        SCROLL = 85,
        SCROLL_SUPPORT = 86,
        WHOLECHAT = ALLCHT,
    }
}
