CREATE TABLE IF NOT EXISTS `setting`
(
    `key`   TEXT NOT NULL,
    `value` TEXT NOT NULL,
    PRIMARY KEY (`key`)
);

CREATE TABLE IF NOT EXISTS `account`
(
    `id`               INTEGER  NOT NULL PRIMARY KEY AUTOINCREMENT,
    `name`             TEXT     NOT NULL,
    `normal_name`      TEXT     NOT NULL,
    `hash`             TEXT     NOT NULL,
    `mail`             TEXT     NOT NULL,
    `mail_verified`    INTEGER  NOT NULL,
    `mail_verified_at` DATETIME DEFAULT NULL,
    `mail_token`       TEXT     DEFAULT NULL,
    `password_token`   TEXT     DEFAULT NULL,
    `state`            INTEGER  NOT NULL,
    `last_login`       DATETIME DEFAULT NULL,
    `created`          DATETIME NOT NULL,
    CONSTRAINT `uq_account_name` UNIQUE (`name`),
    CONSTRAINT `uq_account_normal_name` UNIQUE (`normal_name`),
    CONSTRAINT `uq_account_mail` UNIQUE (`mail`)
);

CREATE TABLE IF NOT EXISTS `nec_soul`
(
    `id`         INTEGER  NOT NULL PRIMARY KEY AUTOINCREMENT,
    `account_id` INTEGER  NOT NULL,
    `name`       TEXT     NOT NULL,
    `level`      INTEGER  NOT NULL,
    `created`    DATETIME NOT NULL,
    `password`   TEXT DEFAULT NULL,
    CONSTRAINT `fk_nec_soul_account_id` FOREIGN KEY (`account_id`) REFERENCES `account` (`id`),
    CONSTRAINT `uq_nec_soul_name` UNIQUE (`name`)
);

CREATE TABLE IF NOT EXISTS `nec_map`
(
    `id`          INTEGER NOT NULL PRIMARY KEY,
    `country`     TEXT    NOT NULL,
    `area`        TEXT    NOT NULL,
    `place`       TEXT    NOT NULL,
    `x`           INTEGER NOT NULL,
    `y`           INTEGER DEFAULT NULL,
    `z`           INTEGER DEFAULT NULL,
    `orientation` INTEGER DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS `nec_character`
(
    `id`               INTEGER  NOT NULL PRIMARY KEY AUTOINCREMENT,
    `account_id`       INTEGER  NOT NULL,
    `soul_id`          INTEGER  NOT NULL,
    `slot`             INTEGER  NOT NULL,
    `map_id`           INTEGER  NOT NULL,
    `x`                REAL     NOT NULL,
    `y`                REAL     NOT NULL,
    `z`                REAL     NOT NULL,
    `name`             TEXT     NOT NULL,
    `race_id`          INTEGER  NOT NULL,
    `sex_id`           INTEGER  NOT NULL,
    `hair_id`          INTEGER  NOT NULL,
    `hair_color_id`    INTEGER  NOT NULL,
    `face_id`          INTEGER  NOT NULL,
    `alignment_id`     INTEGER  NOT NULL,
    `strength`         INTEGER  NOT NULL,
    `vitality`         INTEGER  NOT NULL,
    `dexterity`        INTEGER  NOT NULL,
    `agility`          INTEGER  NOT NULL,
    `intelligence`     INTEGER  NOT NULL,
    `piety`            INTEGER  NOT NULL,
    `luck`             INTEGER  NOT NULL,
    `class_id`         INTEGER  NOT NULL,
    `level`            INTEGER  NOT NULL,
    `shortcut_bar0_id` INTEGER  NOT NULL,
    `shortcut_bar1_id` INTEGER  NOT NULL,
    `shortcut_bar2_id` INTEGER  NOT NULL,
    `shortcut_bar3_id` INTEGER  NOT NULL,
    `shortcut_bar4_id` INTEGER  NOT NULL,
    `created`          DATETIME NOT NULL,
    CONSTRAINT `fk_nec_character_account_id` FOREIGN KEY (`account_id`) REFERENCES `account` (`id`),
    CONSTRAINT `fk_nec_character_soul_id` FOREIGN KEY (`soul_id`) REFERENCES `nec_soul` (`id`),
    CONSTRAINT `fk_nec_character_map_id` FOREIGN KEY (`map_id`) REFERENCES `nec_map` (`id`),
    CONSTRAINT `uq_nec_character_soul_id_name` UNIQUE (`soul_id`, `name`),
    CONSTRAINT `uq_nec_character_soul_id_slot` UNIQUE (`soul_id`, `slot`)
);

CREATE TABLE IF NOT EXISTS `nec_npc_spawn`
(
    `id`         INTEGER  NOT NULL PRIMARY KEY AUTOINCREMENT,
    `npc_id`     INTEGER  NOT NULL,
    `model_id`   INTEGER  NOT NULL,
    `level`      INTEGER  NOT NULL,
    `name`       TEXT     NOT NULL,
    `title`      TEXT     NOT NULL,
    `map_id`     INTEGER  NOT NULL,
    `x`          REAL     NOT NULL,
    `y`          REAL     NOT NULL,
    `z`          REAL     NOT NULL,
    `active`     INTEGER  NOT NULL,
    `heading`    INTEGER  NOT NULL,
    `size`       INTEGER  NOT NULL,
    `visibility` INTEGER  NOT NULL,
    `created`    DATETIME NOT NULL,
    `updated`    DATETIME NOT NULL,
    `icon`       INTEGER  NOT NULL,
    `status`     INTEGER  NOT NULL,
    `status_x`   INTEGER  NOT NULL,
    `status_y`   INTEGER  NOT NULL,
    `status_z`   INTEGER  NOT NULL
);

CREATE TABLE IF NOT EXISTS `nec_monster_spawn`
(
    `id`         INTEGER  NOT NULL PRIMARY KEY AUTOINCREMENT,
    `monster_id` INTEGER  NOT NULL,
    `model_id`   INTEGER  NOT NULL,
    `level`      INTEGER  NOT NULL,
    `name`       TEXT     NOT NULL,
    `title`      TEXT     NOT NULL,
    `map_id`     INTEGER  NOT NULL,
    `x`          REAL     NOT NULL,
    `y`          REAL     NOT NULL,
    `z`          REAL     NOT NULL,
    `active`     INTEGER  NOT NULL,
    `heading`    INTEGER  NOT NULL,
    `size`       INTEGER  NOT NULL,
    `created`    DATETIME NOT NULL,
    `updated`    DATETIME NOT NULL
);

CREATE TABLE IF NOT EXISTS `nec_skilltree_item`
(
    `id`       INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    `skill_id` INTEGER                           NOT NULL,
    `char_id`  INTEGER                           NOT NULL,
    `level`    INTEGER                           NOT NULL
);

CREATE TABLE IF NOT EXISTS `nec_shortcut_bar`
(
    `id`      INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    `slot0`   INTEGER                           NOT NULL,
    `slot1`   INTEGER                           NOT NULL,
    `slot2`   INTEGER                           NOT NULL,
    `slot3`   INTEGER                           NOT NULL,
    `slot4`   INTEGER                           NOT NULL,
    `slot5`   INTEGER                           NOT NULL,
    `slot6`   INTEGER                           NOT NULL,
    `slot7`   INTEGER                           NOT NULL,
    `slot8`   INTEGER                           NOT NULL,
    `slot9`   INTEGER                           NOT NULL,
    `action0` INTEGER                           NOT NULL,
    `action1` INTEGER                           NOT NULL,
    `action2` INTEGER                           NOT NULL,
    `action3` INTEGER                           NOT NULL,
    `action4` INTEGER                           NOT NULL,
    `action5` INTEGER                           NOT NULL,
    `action6` INTEGER                           NOT NULL,
    `action7` INTEGER                           NOT NULL,
    `action8` INTEGER                           NOT NULL,
    `action9` INTEGER                           NOT NULL
);

CREATE TABLE IF NOT EXISTS `nec_monster_coords`
(
    `id`         INTEGER PRIMARY KEY NOT NULL,
    `monster_id` INTEGER             NOT NULL,
    `map_id`     INTEGER             NOT NULL,
    `coord_idx`  INTEGER             NOT NULL,
    `x`          REAL                NOT NULL,
    `y`          REAL                NOT NULL,
    `z`          REAL                NOT NULL
);


CREATE TABLE IF NOT EXISTS `nec_block_list`
(
    `id`            INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    `soul_id`       INTEGER NOT NULL,
    `block_soul_id` INTEGER NOT NULL,
    FOREIGN KEY (`soul_id`) REFERENCES `nec_soul` (`id`),
    FOREIGN KEY (`block_soul_id`) REFERENCES `nec_soul` (`id`)
);

CREATE TABLE IF NOT EXISTS `nec_union`
(
    `id`                        INTEGER  NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
    `name`                      TEXT     NOT NULL,
    `leader_character_id`       INTEGER  NOT NULL,
    `subleader1_character_id`   INTEGER,
    `subleader2_character_id`   INTEGER,
    `level`                     INTEGER  NOT NULL,
    `current_exp`               INTEGER  NOT NULL,
    `next_level_exp`            INTEGER  NOT NULL,
    `member_limit_increase`     INTEGER  NOT NULL,
    `cape_design_id`            INTEGER,
    `union_news`                TEXT,
    `created`                   DATETIME NOT NULL,
    CONSTRAINT `fk_nec_union_leader_character_id` FOREIGN KEY (`leader_character_id`) REFERENCES `nec_character` (`id`)
    --CONSTRAINT `fk_nec_union_subleader1_character_id` FOREIGN KEY (`subleader1_character_id`) REFERENCES `nec_character` (`id`)
    --CONSTRAINT `fk_nec_union_subleader2_character_id` FOREIGN KEY (`subleader2_character_id`) REFERENCES `nec_character` (`id`)
);

CREATE TABLE IF NOT EXISTS `nec_union_member`
(
    `id`                        INTEGER  NOT NULL PRIMARY KEY AUTOINCREMENT,
    `union_id`                  INTEGER  NOT NULL,
    `character_id`              INTEGER  NOT NULL,
    `member_priviledge_bitmask` INTEGER  NOT NULL,
    `rank`                      INTEGER  NOT NULL,
    `joined`                    DATETIME NOT NULL
);

CREATE TABLE IF NOT EXISTS `nec_union_news`
(
    `Id`                  INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
    `character_soul_name` STRING  NOT NULL,
    `character_name`      STRING  NOT NULL,
    `activity`            INTEGER NOT NULL,
    `string3`             STRING,
    `string4`             STRING,
    `itemcount`           INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS `nec_black_list`
(
    `id`            INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    `soul_id`       INTEGER NOT NULL,
    `black_soul_id` INTEGER NOT NULL,
    FOREIGN KEY (`black_soul_id`) REFERENCES `nec_soul` (`id`),
    FOREIGN KEY (`soul_id`) REFERENCES `nec_soul` (`id`)
);

CREATE TABLE IF NOT EXISTS `nec_friend_list`
(
    `id`             INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    `soul_id`        INTEGER NOT NULL,
    `friend_soul_id` INTEGER NOT NULL,
    FOREIGN KEY (`soul_id`) REFERENCES `nec_soul` (`id`),
    FOREIGN KEY (`friend_soul_id`) REFERENCES `nec_soul` (`id`)
);

CREATE TABLE IF NOT EXISTS `nec_gimmick_spawn`
(
    `id`       INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    `map_id`   INTEGER NOT NULL,
    `x`        INTEGER NOT NULL,
    `y`        INTEGER NOT NULL,
    `z`        INTEGER NOT NULL,
    `heading`  INTEGER NOT NULL,
    `model_id` INTEGER NOT NULL,
    `state`    INTEGER NOT NULL,
    `created`  DATETIME,
    `updated`  DATETIME
);

CREATE TABLE IF NOT EXISTS `nec_map_transition`
(
    `id`                INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    `map_id`            INTEGER NOT NULL,
    `transition_map_id` INTEGER NOT NULL,
    `x`                 REAL    NOT NULL,
    `y`                 REAL    NOT NULL,
    `z`                 REAL    NOT NULL,
    `maplink_heading`   INTEGER NOT NULL,
    `maplink_color`     INTEGER NOT NULL,
    `maplink_offset`    INTEGER NOT NULL,
    `maplink_width`     INTEGER NOT NULL,
    `distance`          INTEGER NOT NULL,
    `left_x`            REAL    NOT NULL,
    `left_y`            REAL    NOT NULL,
    `left_z`            REAL    NOT NULL,
    `right_x`           REAL    NOT NULL,
    `right_y`           REAL    NOT NULL,
    `right_z`           REAL    NOT NULL,
    `invertedPos`       INTEGER NOT NULL,
    `to_x`              REAL    NOT NULL,
    `to_y`              REAL    NOT NULL,
    `to_z`              REAL    NOT NULL,
    `to_heading`        INTEGER NOT NULL,
    `state`             INTEGER NOT NULL,
    `created`           DATETIME,
    `updated`           DATETIME
);

CREATE TABLE IF NOT EXISTS `nec_ggate_spawn`
(
    `id`          INTEGER PRIMARY KEY NOT NULL,
    `serial_id`   INTEGER             NOT NULL,
    `interaction` INTEGER             NOT NULL,
    `name`        TEXT                NOT NULL,
    `title`       TEXT                NOT NULL,
    `map_id`      INTEGER             NOT NULL,
    `x`           REAL                NOT NULL,
    `y`           REAL                NOT NULL,
    `z`           REAL                NOT NULL,
    `heading`     INTEGER             NOT NULL,
    `model_id`    INTEGER             NOT NULL,
    `size`        INTEGER             NOT NULL,
    `active`      INTEGER             NOT NULL,
    `glow`        INTEGER             NOT NULL,
    `created`     DATETIME            NOT NULL,
    `updated`     DATETIME            NOT NULL
);

--Inventory and Item Related tables

CREATE TABLE IF NOT EXISTS `nec_item_library`
(
    `id`                  INTEGER NOT NULL PRIMARY KEY,
    `name`                TEXT    NOT NULL,
    `item_type`           INTEGER NOT NULL,
    `equipment_slot_type` INTEGER NOT NULL,
    `physical`            INTEGER NOT NULL,
    `magical`             INTEGER NOT NULL,
    `durability`          INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS `nec_item_spawn` (
	`id`	                INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	`character_id`	        INTEGER NOT NULL,
	`item_id`	            INTEGER NOT NULL,
	`quantity`	            INTEGER NOT NULL,
	`current_durability`	INTEGER NOT NULL,
	CONSTRAINT `fk_nec_item_spawn_item_id` FOREIGN KEY(`item_id`) REFERENCES `nec_item_library`(`id`)
);

CREATE TABLE IF NOT EXISTS `nec_item_character_bag` (
	`id`	    INTEGER NOT NULL,
	`char_id`	INTEGER NOT NULL,
	`1`	        INTEGER,
	`2`	        INTEGER,
	`3`	        INTEGER,
	`4`	        INTEGER,
	`5`	        INTEGER,
	PRIMARY KEY(`id`),
	CONSTRAINT `fk_nec_item_character_bag_character_id` FOREIGN KEY(`char_id`) REFERENCES `nec_character`(`id`)
);

CREATE TABLE IF NOT EXISTS `nec_item_character_inventory` (
	`id`	    INTEGER NOT NULL,
	`char_id`	INTEGER NOT NULL,
	`1.1`	    INTEGER,
	`1.2`	    INTEGER,
	`1.3`	    INTEGER,
	`1.4`	    INTEGER,
	`1.5`	    INTEGER,
	`1.6`	    INTEGER,	
	`1.7`	    INTEGER,
	`1.8`	    INTEGER,
	`1.9`	    INTEGER,
	`1.10`	    INTEGER,
	`1.11`	    INTEGER,
	`1.12`	    INTEGER,
	`1.13`	    INTEGER,
	`1.14`	    INTEGER,
	`1.15`	    INTEGER,
	`1.16`	    INTEGER,	
	`1.17`	    INTEGER,
	`1.18`	    INTEGER,
	`1.19`	    INTEGER,
	`1.20`	    INTEGER,
	`1.21`	    INTEGER,
	`1.22`	    INTEGER,
	`1.23`	    INTEGER,
	`1.24`	    INTEGER,
	`2.1`	    INTEGER,
	`2.2`	    INTEGER,
	`2.3`	    INTEGER,
	`2.4`	    INTEGER,
	`2.5`	    INTEGER,
	`2.6`	    INTEGER,	
	`2.7`	    INTEGER,
	`2.8`	    INTEGER,
	`2.9`	    INTEGER,
	`2.10`	    INTEGER,
	`2.11`	    INTEGER,
	`2.12`	    INTEGER,
	`2.13`	    INTEGER,
	`2.14`	    INTEGER,
	`2.15`	    INTEGER,
	`2.16`	    INTEGER,	
	`2.17`	    INTEGER,
	`2.18`	    INTEGER,
	`2.19`	    INTEGER,
	`2.20`	    INTEGER,
	`2.21`	    INTEGER,
	`2.22`	    INTEGER,
	`2.23`	    INTEGER,
	`2.24`	    INTEGER,
	`3.1`	    INTEGER,
	`3.2`	    INTEGER,
	`3.3`	    INTEGER,
	`3.4`	    INTEGER,
	`3.5`	    INTEGER,
	`3.6`	    INTEGER,	
	`3.7`	    INTEGER,
	`3.8`	    INTEGER,
	`3.9`	    INTEGER,
	`3.10`	    INTEGER,
	`3.11`	    INTEGER,
	`3.12`	    INTEGER,
	`3.13`	    INTEGER,
	`3.14`	    INTEGER,
	`3.15`	    INTEGER,
	`3.16`	    INTEGER,	
	`3.17`	    INTEGER,
	`3.18`	    INTEGER,
	`3.19`	    INTEGER,
	`3.20`	    INTEGER,
	`3.21`	    INTEGER,
	`3.22`	    INTEGER,
	`3.23`	    INTEGER,
	`3.24`	    INTEGER,	
	`4.1`	    INTEGER,
	`4.2`	    INTEGER,
	`4.3`	    INTEGER,
	`4.4`	    INTEGER,
	`4.5`	    INTEGER,
	`4.6`	    INTEGER,	
	`4.7`	    INTEGER,
	`4.8`	    INTEGER,
	`4.9`	    INTEGER,
	`4.10`	    INTEGER,
	`4.11`	    INTEGER,
	`4.12`	    INTEGER,
	`4.13`	    INTEGER,
	`4.14`	    INTEGER,
	`4.15`	    INTEGER,
	`4.16`	    INTEGER,	
	`4.17`	    INTEGER,
	`4.18`	    INTEGER,
	`4.19`	    INTEGER,
	`4.20`	    INTEGER,
	`4.21`	    INTEGER,
	`4.22`	    INTEGER,
	`4.23`	    INTEGER,
	`4.24`	    INTEGER,
	`5.1`	    INTEGER,
	`5.2`	    INTEGER,
	`5.3`	    INTEGER,
	`5.4`	    INTEGER,
	`5.5`	    INTEGER,
	`5.6`	    INTEGER,	
	`5.7`	    INTEGER,
	`5.8`	    INTEGER,
	`5.9`	    INTEGER,
	`5.10`	    INTEGER,
	`5.11`	    INTEGER,
	`5.12`	    INTEGER,
	`5.13`	    INTEGER,
	`5.14`	    INTEGER,
	`5.15`	    INTEGER,
	`5.16`	    INTEGER,	
	`5.17`	    INTEGER,
	`5.18`	    INTEGER,
	`5.19`	    INTEGER,
	`5.20`	    INTEGER,
	`5.21`	    INTEGER,
	`5.22`	    INTEGER,
	`5.23`	    INTEGER,
	`5.24`	    INTEGER,	
	PRIMARY KEY(`id`),
	CONSTRAINT `fk_nec_item_character_inventory_character_id` FOREIGN KEY(`char_id`) REFERENCES `nec_character`(`id`)
);

CREATE TABLE IF NOT EXISTS `nec_item_character_equipment` (
	`id`	    INTEGER NOT NULL,
	`char_id`	INTEGER NOT NULL,
	`1.1`	    INTEGER,
	`1.2`	    INTEGER,
	`1.3`	    INTEGER,
	`1.4`	    INTEGER,
	`1.5`	    INTEGER,
	`1.6`	    INTEGER,	
	`1.7`	    INTEGER,
	`1.8`	    INTEGER,
	`1.9`	    INTEGER,
	`1.10`	    INTEGER,
	`1.11`	    INTEGER,
	`1.12`	    INTEGER,
	`1.13`	    INTEGER,
	`1.14`	    INTEGER,
	`1.15`	    INTEGER,
	`1.16`	    INTEGER,	
	`1.17`	    INTEGER,
	`1.18`	    INTEGER,
	`1.19`	    INTEGER,
	PRIMARY KEY(`id`),
	CONSTRAINT `fk_nec_item_character_equipment_character_id` FOREIGN KEY(`char_id`) REFERENCES `nec_character`(`id`)
);
CREATE TABLE IF NOT EXISTS `nec_item_avatar_inventory` (
	`id`	    INTEGER NOT NULL,
	`char_id`	INTEGER NOT NULL,
	`1.1`	    INTEGER,
	`1.2`	    INTEGER,
	`1.3`	    INTEGER,
	`1.4`	    INTEGER,
	`1.5`	    INTEGER,
	`1.6`	    INTEGER,	
	`1.7`	    INTEGER,
	`1.8`	    INTEGER,
	`1.9`	    INTEGER,
	`1.10`	    INTEGER,
	`1.11`	    INTEGER,
	`1.12`	    INTEGER,
	`1.13`	    INTEGER,
	`1.14`	    INTEGER,
	`1.15`	    INTEGER,
	`1.16`	    INTEGER,	
	`1.17`	    INTEGER,
	`1.18`	    INTEGER,
	`1.19`	    INTEGER,
	`1.20`	    INTEGER,
	`1.21`	    INTEGER,
	`1.22`	    INTEGER,
	`1.23`	    INTEGER,
	`1.24`	    INTEGER,
	`1.25`	    INTEGER,
	`1.26`	    INTEGER,	
	`1.27`	    INTEGER,
	`1.28`	    INTEGER,
	`1.29`	    INTEGER,
	`1.30`	    INTEGER,
	`1.31`	    INTEGER,
	`1.32`	    INTEGER,
	`1.33`	    INTEGER,
	`1.34`	    INTEGER,
	`1.35`	    INTEGER,
	`1.36`	    INTEGER,	
	`1.37`	    INTEGER,
	`1.38`	    INTEGER,
	`1.39`	    INTEGER,
	`1.40`	    INTEGER,
	`1.41`	    INTEGER,
	`1.42`	    INTEGER,
	`1.43`	    INTEGER,
	`1.44`	    INTEGER,
	`1.45`	    INTEGER,
	`1.46`	    INTEGER,	
	`1.47`	    INTEGER,
	`1.48`	    INTEGER,
	`1.49`	    INTEGER,
	`1.50`	    INTEGER,
	`2.1`	    INTEGER,
	`2.2`	    INTEGER,
	`2.3`	    INTEGER,
	`2.4`	    INTEGER,
	`2.5`	    INTEGER,
	`2.6`	    INTEGER,	
	`2.7`	    INTEGER,
	`2.8`	    INTEGER,
	`2.9`	    INTEGER,
	`2.10`	    INTEGER,
	`2.11`	    INTEGER,
	`2.12`	    INTEGER,
	`2.13`	    INTEGER,
	`2.14`	    INTEGER,
	`2.15`	    INTEGER,
	`2.16`	    INTEGER,	
	`2.17`	    INTEGER,
	`2.18`	    INTEGER,
	`2.19`	    INTEGER,
	`2.20`	    INTEGER,
	`2.21`	    INTEGER,
	`2.22`	    INTEGER,
	`2.23`	    INTEGER,
	`2.24`	    INTEGER,
	`2.25`	    INTEGER,
	`2.26`	    INTEGER,	
	`2.27`	    INTEGER,
	`2.28`	    INTEGER,
	`2.29`	    INTEGER,
	`2.30`	    INTEGER,
	`2.31`	    INTEGER,
	`2.32`	    INTEGER,
	`2.33`	    INTEGER,
	`2.34`	    INTEGER,
	`2.35`	    INTEGER,
	`2.36`	    INTEGER,	
	`2.37`	    INTEGER,
	`2.38`	    INTEGER,
	`2.39`	    INTEGER,
	`2.40`	    INTEGER,
	`2.41`	    INTEGER,
	`2.42`	    INTEGER,
	`2.43`	    INTEGER,
	`2.44`	    INTEGER,
	`2.45`	    INTEGER,
	`2.46`	    INTEGER,	
	`2.47`	    INTEGER,
	`2.48`	    INTEGER,
	`2.49`	    INTEGER,
	`2.50`	    INTEGER,	
	`3.1`	    INTEGER,
	`3.2`	    INTEGER,
	`3.3`	    INTEGER,
	`3.4`	    INTEGER,
	`3.5`	    INTEGER,
	`3.6`	    INTEGER,	
	`3.7`	    INTEGER,
	`3.8`	    INTEGER,
	`3.9`	    INTEGER,
	`3.10`	    INTEGER,
	`3.11`	    INTEGER,
	`3.12`	    INTEGER,
	`3.13`	    INTEGER,
	`3.14`	    INTEGER,
	`3.15`	    INTEGER,
	`3.16`	    INTEGER,	
	`3.17`	    INTEGER,
	`3.18`	    INTEGER,
	`3.19`	    INTEGER,
	`3.20`	    INTEGER,
	`3.21`	    INTEGER,
	`3.22`	    INTEGER,
	`3.23`	    INTEGER,
	`3.24`	    INTEGER,
	`3.25`	    INTEGER,
	`3.26`	    INTEGER,	
	`3.27`	    INTEGER,
	`3.28`	    INTEGER,
	`3.29`	    INTEGER,
	`3.30`	    INTEGER,
	`3.31`	    INTEGER,
	`3.32`	    INTEGER,
	`3.33`	    INTEGER,
	`3.34`	    INTEGER,
	`3.35`	    INTEGER,
	`3.36`	    INTEGER,	
	`3.37`	    INTEGER,
	`3.38`	    INTEGER,
	`3.39`	    INTEGER,
	`3.40`	    INTEGER,
	`3.41`	    INTEGER,
	`3.42`	    INTEGER,
	`3.43`	    INTEGER,
	`3.44`	    INTEGER,
	`3.45`	    INTEGER,
	`3.46`	    INTEGER,	
	`3.47`	    INTEGER,
	`3.48`	    INTEGER,
	`3.49`	    INTEGER,
	`3.50`	    INTEGER,
	PRIMARY KEY(`id`),
	CONSTRAINT `fk_nec_item_avatar_inventory_character_id` FOREIGN KEY(`char_id`) REFERENCES `nec_character`(`id`)
);



CREATE TABLE IF NOT EXISTS `nec_item_soul_inventory` (
	`id`	    INTEGER NOT NULL,
	`soul_id`	INTEGER NOT NULL,
	`1.1`	    INTEGER,
	`1.2`	    INTEGER,
	`1.3`	    INTEGER,
	`1.4`	    INTEGER,
	`1.5`	    INTEGER,
	`1.6`	    INTEGER,	
	`1.7`	    INTEGER,
	`1.8`	    INTEGER,
	`1.9`	    INTEGER,
	`1.10`	    INTEGER,
	`1.11`	    INTEGER,
	`1.12`	    INTEGER,
	`1.13`	    INTEGER,
	`1.14`	    INTEGER,
	`1.15`	    INTEGER,
	`1.16`	    INTEGER,	
	`1.17`	    INTEGER,
	`1.18`	    INTEGER,
	`1.19`	    INTEGER,
	`1.20`	    INTEGER,
	`1.21`	    INTEGER,
	`1.22`	    INTEGER,
	`1.23`	    INTEGER,
	`1.24`	    INTEGER,
	`1.25`	    INTEGER,
	`1.26`	    INTEGER,	
	`1.27`	    INTEGER,
	`1.28`	    INTEGER,
	`1.29`	    INTEGER,
	`1.30`	    INTEGER,
	`2.1`	    INTEGER,
	`2.2`	    INTEGER,
	`2.3`	    INTEGER,
	`2.4`	    INTEGER,
	`2.5`	    INTEGER,
	`2.6`	    INTEGER,	
	`2.7`	    INTEGER,
	`2.8`	    INTEGER,
	`2.9`	    INTEGER,
	`2.10`	    INTEGER,
	`2.11`	    INTEGER,
	`2.12`	    INTEGER,
	`2.13`	    INTEGER,
	`2.14`	    INTEGER,
	`2.15`	    INTEGER,
	`2.16`	    INTEGER,	
	`2.17`	    INTEGER,
	`2.18`	    INTEGER,
	`2.19`	    INTEGER,
	`2.20`	    INTEGER,
	`2.21`	    INTEGER,
	`2.22`	    INTEGER,
	`2.23`	    INTEGER,
	`2.24`	    INTEGER,
	`2.25`	    INTEGER,
	`2.26`	    INTEGER,	
	`2.27`	    INTEGER,
	`2.28`	    INTEGER,
	`2.29`	    INTEGER,
	`2.30`	    INTEGER,	
	`3.1`	    INTEGER,
	`3.2`	    INTEGER,
	`3.3`	    INTEGER,
	`3.4`	    INTEGER,
	`3.5`	    INTEGER,
	`3.6`	    INTEGER,	
	`3.7`	    INTEGER,
	`3.8`	    INTEGER,
	`3.9`	    INTEGER,
	`3.10`	    INTEGER,
	`3.11`	    INTEGER,
	`3.12`	    INTEGER,
	`3.13`	    INTEGER,
	`3.14`	    INTEGER,
	`3.15`	    INTEGER,
	`3.16`	    INTEGER,	
	`3.17`	    INTEGER,
	`3.18`	    INTEGER,
	`3.19`	    INTEGER,
	`3.20`	    INTEGER,
	`3.21`	    INTEGER,
	`3.22`	    INTEGER,
	`3.23`	    INTEGER,
	`3.24`	    INTEGER,
	`3.25`	    INTEGER,
	`3.26`	    INTEGER,	
	`3.27`	    INTEGER,
	`3.28`	    INTEGER,
	`3.29`	    INTEGER,
	`3.30`	    INTEGER,
	`4.1`	    INTEGER,
	`4.2`	    INTEGER,
	`4.3`	    INTEGER,
	`4.4`	    INTEGER,
	`4.5`	    INTEGER,
	`4.6`	    INTEGER,	
	`4.7`	    INTEGER,
	`4.8`	    INTEGER,
	`4.9`	    INTEGER,
	`4.10`	    INTEGER,
	`4.11`	    INTEGER,
	`4.12`	    INTEGER,
	`4.13`	    INTEGER,
	`4.14`	    INTEGER,
	`4.15`	    INTEGER,
	`4.16`	    INTEGER,	
	`4.17`	    INTEGER,
	`4.18`	    INTEGER,
	`4.19`	    INTEGER,
	`4.20`	    INTEGER,
	`4.21`	    INTEGER,
	`4.22`	    INTEGER,
	`4.23`	    INTEGER,
	`4.24`	    INTEGER,
	`4.25`	    INTEGER,
	`4.26`	    INTEGER,	
	`4.27`	    INTEGER,
	`4.28`	    INTEGER,
	`4.29`	    INTEGER,
	`4.30`	    INTEGER,
	`5.1`	    INTEGER,
	`5.2`	    INTEGER,
	`5.3`	    INTEGER,
	`5.4`	    INTEGER,
	`5.5`	    INTEGER,
	`5.6`	    INTEGER,	
	`5.7`	    INTEGER,
	`5.8`	    INTEGER,
	`5.9`	    INTEGER,
	`5.10`	    INTEGER,
	`5.11`	    INTEGER,
	`5.12`	    INTEGER,
	`5.13`	    INTEGER,
	`5.14`	    INTEGER,
	`5.15`	    INTEGER,
	`5.16`	    INTEGER,	
	`5.17`	    INTEGER,
	`5.18`	    INTEGER,
	`5.19`	    INTEGER,
	`5.20`	    INTEGER,
	`5.21`	    INTEGER,
	`5.22`	    INTEGER,
	`5.23`	    INTEGER,
	`5.24`	    INTEGER,
	`5.25`	    INTEGER,
	`5.26`	    INTEGER,	
	`5.27`	    INTEGER,
	`5.28`	    INTEGER,
	`5.29`	    INTEGER,
	`5.30`	    INTEGER,	
	`6.1`	    INTEGER,
	`6.2`	    INTEGER,
	`6.3`	    INTEGER,
	`6.4`	    INTEGER,
	`6.5`	    INTEGER,
	`6.6`	    INTEGER,	
	`6.7`	    INTEGER,
	`6.8`	    INTEGER,
	`6.9`	    INTEGER,
	`6.10`	    INTEGER,
	`6.11`	    INTEGER,
	`6.12`	    INTEGER,
	`6.13`	    INTEGER,
	`6.14`	    INTEGER,
	`6.15`	    INTEGER,
	`6.16`	    INTEGER,	
	`6.17`	    INTEGER,
	`6.18`	    INTEGER,
	`6.19`	    INTEGER,
	`6.20`	    INTEGER,
	`6.21`	    INTEGER,
	`6.22`	    INTEGER,
	`6.23`	    INTEGER,
	`6.24`	    INTEGER,
	`6.25`	    INTEGER,
	`6.26`	    INTEGER,	
	`6.27`	    INTEGER,
	`6.28`	    INTEGER,
	`6.29`	    INTEGER,
	`6.30`	    INTEGER,
	`7.1`	    INTEGER,
	`7.2`	    INTEGER,
	`7.3`	    INTEGER,
	`7.4`	    INTEGER,
	`7.5`	    INTEGER,
	`7.6`	    INTEGER,	
	`7.7`	    INTEGER,
	`7.8`	    INTEGER,
	`7.9`	    INTEGER,
	`7.10`	    INTEGER,
	`7.11`	    INTEGER,
	`7.12`	    INTEGER,
	`7.13`	    INTEGER,
	`7.14`	    INTEGER,
	`7.15`	    INTEGER,
	`7.16`	    INTEGER,	
	`7.17`	    INTEGER,
	`7.18`	    INTEGER,
	`7.19`	    INTEGER,
	`7.20`	    INTEGER,
	`7.21`	    INTEGER,
	`7.22`	    INTEGER,
	`7.23`	    INTEGER,
	`7.24`	    INTEGER,
	`7.25`	    INTEGER,
	`7.26`	    INTEGER,	
	`7.27`	    INTEGER,
	`7.28`	    INTEGER,
	`7.29`	    INTEGER,
	`7.30`	    INTEGER,
	`8.1`	    INTEGER,
	`8.2`	    INTEGER,
	`8.3`	    INTEGER,
	`8.4`	    INTEGER,
	`8.5`	    INTEGER,
	`8.6`	    INTEGER,	
	`8.7`	    INTEGER,
	`8.8`	    INTEGER,
	`8.9`	    INTEGER,
	`8.10`	    INTEGER,
	`8.11`	    INTEGER,
	`8.12`	    INTEGER,
	`8.13`	    INTEGER,
	`8.14`	    INTEGER,
	`8.15`	    INTEGER,
	`8.16`	    INTEGER,	
	`8.17`	    INTEGER,
	`8.18`	    INTEGER,
	`8.19`	    INTEGER,
	`8.20`	    INTEGER,
	`8.21`	    INTEGER,
	`8.22`	    INTEGER,
	`8.23`	    INTEGER,
	`8.24`	    INTEGER,
	`8.25`	    INTEGER,
	`8.26`	    INTEGER,	
	`8.27`	    INTEGER,
	`8.28`	    INTEGER,
	`8.29`	    INTEGER,
	`8.30`	    INTEGER,	
	`9.1`	    INTEGER,
	`9.2`	    INTEGER,
	`9.3`	    INTEGER,
	`9.4`	    INTEGER,
	`9.5`	    INTEGER,
	`9.6`	    INTEGER,	
	`9.7`	    INTEGER,
	`9.8`	    INTEGER,
	`9.9`	    INTEGER,
	`9.10`	    INTEGER,
	`9.11`	    INTEGER,
	`9.12`	    INTEGER,
	`9.13`	    INTEGER,
	`9.14`	    INTEGER,
	`9.15`	    INTEGER,
	`9.16`	    INTEGER,	
	`9.17`	    INTEGER,
	`9.18`	    INTEGER,
	`9.19`	    INTEGER,
	`9.20`	    INTEGER,
	`9.21`	    INTEGER,
	`9.22`	    INTEGER,
	`9.23`	    INTEGER,
	`9.24`	    INTEGER,
	`9.25`	    INTEGER,
	`9.26`	    INTEGER,	
	`9.27`	    INTEGER,
	`9.28`	    INTEGER,
	`9.29`	    INTEGER,
	`9.30`	    INTEGER,	
	PRIMARY KEY(`id`),
	CONSTRAINT `fk_nec_item_soul_inventory_soul_id` FOREIGN KEY(`soul_id`) REFERENCES `nec_soul`(`id`)
);

CREATE TABLE IF NOT EXISTS `nec_item_union_iventory` (
	`id`	    INTEGER NOT NULL,
	`union_id`	INTEGER NOT NULL,
	`1.1`	    INTEGER,
	`1.2`	    INTEGER,
	`1.3`	    INTEGER,
	`1.4`	    INTEGER,
	`1.5`	    INTEGER,
	`1.6`	    INTEGER,	
	`1.7`	    INTEGER,
	`1.8`	    INTEGER,
	`1.9`	    INTEGER,
	`1.10`	    INTEGER,
	`1.11`	    INTEGER,
	`1.12`	    INTEGER,
	`1.13`	    INTEGER,
	`1.14`	    INTEGER,
	`1.15`	    INTEGER,
	`1.16`	    INTEGER,	
	`1.17`	    INTEGER,
	`1.18`	    INTEGER,
	`1.19`	    INTEGER,
	`1.20`	    INTEGER,
	`1.21`	    INTEGER,
	`1.22`	    INTEGER,
	`1.23`	    INTEGER,
	`1.24`	    INTEGER,
	`1.25`	    INTEGER,
	`1.26`	    INTEGER,	
	`1.27`	    INTEGER,
	`1.28`	    INTEGER,
	`1.29`	    INTEGER,
	`1.30`	    INTEGER,	
	`1.31`	    INTEGER,
	`1.32`	    INTEGER,
	`1.33`	    INTEGER,
	`1.34`	    INTEGER,
	`1.35`	    INTEGER,
	`1.36`	    INTEGER,	
	`1.37`	    INTEGER,
	`1.38`	    INTEGER,
	`1.39`	    INTEGER,
	`1.40`	    INTEGER,
	`1.41`	    INTEGER,
	`1.42`	    INTEGER,
	`1.43`	    INTEGER,
	`1.44`	    INTEGER,
	`1.45`	    INTEGER,
	`1.46`	    INTEGER,	
	`1.47`	    INTEGER,
	`1.48`	    INTEGER,
	`1.49`	    INTEGER,
	`1.50`	    INTEGER,	
	CONSTRAINT `fk_nec_item_union_inventory_union_id` FOREIGN KEY(`union_id`) REFERENCES `nec_union`(`id`),
	PRIMARY KEY(`id`)
);
