// ReSharper disable InconsistentNaming

namespace Necromancy.Server.Packet.Id
{

    public enum AreaPacketId : ushort
    {
        recv_base_check_version_r = 0xEFDD, // this is being used to test other opcodes the normal value should be (0xEFDD)

        // Recv OP Codes - Switch: 0x495B88 - ordered by op code
        recv_0x1D09 = 0x1D09, //recv_party_notify_update_body_pos
        recv_0x10DA = 0x10DA, // Crash
        recv_0x1489 = 0x1489, // Crash
        recv_0x166B = 0x166B, // Crash
        recv_0x218A = 0x218A, // Doesnt 'crash
        recv_0x287A = 0x287A, // Crash
        recv_0x28A0 = 0x28A0, // Crash 
        recv_0x29C5 = 0x29C5, // Doesn't crash
        recv_0x3A0E = 0x3A0E, // Doesn't crash
        recv_0x3C81 = 0x3C81, // Crash
        recv_0x3F2F = 0x3F2F, // Crash
        recv_0x488D = 0x488D, // Crash
        recv_0x4978 = 0x4978, // Crash
        recv_0x4981 = 0x4981, // Crash
        recv_0x4ABB = 0x4ABB, // Crash
        recv_0x4CF3 = 0x4CF3, // doesn't crash
        recv_0x50D1 = 0x50D1, // Doesn't crash
        recv_0x531B = 0x531B, // Crash
        recv_0x5513 = 0x5513, // Crash
        recv_0x692A = 0x692A, // Crash
        recv_0x6B6A = 0x6B6A, // Crash
        recv_0x735E = 0x735E, // Doesn't Crash
        recv_0x746F = 0x746F, // Crash
        recv_0x755C = 0x755C, // Crash
        recv_0x7697 = 0x7697, // Crash
        recv_0x7B86 = 0x7B86, // Crash
        recv_0x8066 = 0x8066, // Crash
        recv_0x825D = 0x825D, // Crash
        recv_0x8364 = 0x8364, // Doesn't crash
        recv_0x8487 = 0x8487, // Doesn't crash
        recv_0x8549 = 0x8549, // Doesn't crash
        recv_0x8D62 = 0x8D62, // crash
        recv_0x8D92 = 0x8D92, // Crash
        recv_0x9201 = 0x9201, // Crash
        recv_0x97D9 = 0x97D9, // Crash
        recv_0x9899 = 0x9899, // Crash
        recv_0x9CA1 = 0x9CA1, // Cause Crash
        recv_0xA8BB = 0xA8BB, // Cause Crash
        recv_0xA90C = 0xA90C, // Doesn't crash 
        recv_0xABC5 = 0xABC5, // Doesn't Crash
        recv_0xB317 = 0xB317, // Cause Crash
        recv_0xB39D = 0xB39D, // Cause Crash
        recv_0xB586 = 0xB586, // Doesn't crash
        recv_0xB684 = 0xB684, // Cause crash
        recv_0xBA61 = 0xBA61, // Cause Crash
        recv_0xC055 = 0xC055, // Doesn't crash
        recv_0xC078 = 0xC078, // cause Crash
        recv_0xCF29 = 0xCF29, // Cause crash
        recv_0xD04A = 0xD04A, // Cause crash
        recv_0xD1F6 = 0xD1F6, // Cause crash
        recv_0xD909 = 0xD909, // Doesn't crash
        recv_0xDA4A = 0xDA4A, // Doesn't crash
        recv_0xEE18 = 0xEE18, // Cause crash
        recv_0xEEB7 = 0xEEB7, // cause crash
        recv_battle_report_action_attack_onhit = 0xF212, // was previously labeled as recv_battle_report_action_attack_onhit : Confirmed Recv String
        recv_0xFA0B = 0xFA0B, // res.WriteInt32(client.Character.Id); doesn't crash
        recv_0xFB79 = 0xFB79, //   res.WriteInt32(0); doesn't crash too
        recv_0xE8B9 = 0xE8B9, // res.WriteInt32(client.Character.Id); cause crash
        recv_0x1FC1 = 0x1FC1, // res.WriteInt32(client.Character.Id); cause crash
        recv_auction_bid_r = 0x3F38,
        recv_auction_cancel_bid_r = 0xA0FC,
        recv_auction_cancel_exhibit_r = 0xFC28,
        recv_auction_close_r = 0xD1CB,
        recv_auction_exhibit_r = 0xB38D,
        recv_auction_notify_close = 0x7D2B,
        recv_auction_notify_open = 0xBA71,
        recv_auction_re_exhibit_r = 0xA549,
        recv_auction_receive_gold_r = 0x22C,
        recv_auction_receive_item_r = 0xB1CA,
        recv_auction_search_r = 0xF7E7,
        recv_auction_update_bid_item_state = 0x2E17,
        recv_auction_update_bid_num = 0x9BC6,
        recv_auction_update_exhibit_item_state = 0x5307,
        recv_auction_update_highest_bid = 0xBD99,
      //recv_base_check_version_r = 0xEFDD,
        recv_base_enter_r = 0x3806,
        recv_base_exit_r = 0xDA5C,
        recv_base_ping_r = 0xD2D6,
        recv_battle_attack_cancel_r = 0x9666,
        recv_battle_attack_exec_r = 0xF1A0, // 0x998F - recv_battle_attack_exec_direct_r and then 0xF1A0 - recv_battle_attack_exec_r?
        recv_battle_attack_exec_direct_r = 0x998F,
        recv_battle_attack_next_r = 0x68E7,
        recv_battle_attack_pose = 0x0, //todo
        recv_battle_attack_pose_end_notify = 0xF633,
        recv_battle_attack_pose_r = 0x5DEB,
        recv_battle_attack_pose_self = 0x9F74,
        recv_battle_attack_pose_start_notify = 0x7CB2,
        recv_battle_attack_start = 0xD752, //1 other possible inside 0xD68C + 0xC6 - 0x004C8EE5
        recv_battle_attack_start_r = 0xD752,
        recv_battle_charge_end_r = 0x5AE9,
        recv_battle_charge_start_r = 0x4F10,
        recv_battle_guard_end_r = 0xAB8A,
        recv_battle_guard_end_self = 0x5E48,
        recv_battle_guard_start_r = 0xADC8,
        recv_battle_guard_start_self = 0x1E96,
        recv_battle_life_notify = 0x1E2, // opcode not found
        recv_battle_release_attack_pose = 0x0, //todo
        recv_battle_release_attack_pose_r = 0xE990,
        recv_battle_release_attack_pose_self = 0x4EF4,
        recv_battle_report_action_attack_exec = 0xB3F7,
        recv_battle_report_action_attack_failed = 0x877C,
        recv_battle_report_action_cover = 0xCC54,
        recv_battle_report_action_effect_onhit = 0x5899,
        recv_battle_report_action_eq_break = 0xD426,
        recv_battle_report_action_fall = 0x3D9F,
        recv_battle_report_action_item_enchant = 0x6BDC,
        recv_battle_report_action_item_use = 0xD493,
        recv_battle_report_action_monster_skill_exec = 0x2A82,
        recv_battle_report_action_monster_skill_start_cast = 0x1959,
        recv_battle_report_action_removetrap_ontrap = 0x8820,
        recv_battle_report_action_removetrap_success = 0xDB53,
        recv_battle_report_action_skill_cancel = 0x8E92,
        recv_battle_report_action_skill_exec = 0x604,
        recv_battle_report_action_skill_failed = 0xE897,
        recv_battle_report_action_skill_onhit = 0xC701,
        recv_battle_report_action_skill_start_cast = 0x39FD,
        recv_battle_report_action_steal = 0x6E06,
        recv_battle_report_action_steal_unidentified = 0xDC5B,
        recv_battle_report_end_notify = 0x1DBE,
        recv_battle_report_noact_combo_bonus_damage = 0x6DF4,
        recv_battle_report_noact_notify_buff_attach = 0x362D,
        recv_battle_report_noact_notify_buff_attach_failed = 0xCE36,
        recv_battle_report_noact_notify_buff_detach = 0x19AC,
        recv_battle_report_noact_notify_buff_effect = 0xDB5E,
        recv_battle_report_noact_notify_buff_move = 0x65EE,
        recv_battle_report_noact_notify_buff_update_time = 0x19C3,
        recv_battle_report_noact_notify_dead = 0xCDC9,
        recv_battle_report_noact_notify_freeze = 0x129B,
        recv_battle_report_noact_notify_heal_ac = 0xD607,
        recv_battle_report_noact_notify_heal_condition = 0xA938,
        recv_battle_report_noact_notify_heal_life = 0xCA35,
        recv_battle_report_noact_notify_heal_mp = 0xD8D5,
        recv_battle_report_noact_notify_knockback = 0xC2A1,
        recv_battle_report_notify_action_bonus = 0xC235,
        recv_battle_report_notify_attack_hitstate = 0xAF76,
        recv_battle_report_notify_damage_ac = 0xF393,
        recv_battle_report_notify_damage_hp = 0x904,
        recv_battle_report_notify_damage_mp = 0xFD41,
        recv_battle_report_notify_exp = 0xE526,
        recv_battle_report_notify_exp2 = 0x4898,
        recv_battle_report_notify_exp_bonus = 0x7181,
        recv_battle_report_notify_exp_bonus2 = 0xEB47,
        recv_battle_report_notify_hit_effect = 0x179D,
        recv_battle_report_notify_hit_effect_name = 0xB037,
        recv_battle_report_notify_invalid_target = 0xD7D8,
        recv_battle_report_notify_phy_damage_hp = 0x173C,
        recv_battle_report_notify_raise = 0x65D5,
        recv_battle_report_notify_rookie = 0xBD90,
        recv_battle_report_notify_soul_material = 0xC9FF,
        recv_battle_report_notify_soul_point = 0x2513,
        recv_battle_report_start_notify = 0xFC75,
        recv_blacklist_clear_r = 0x1E6B,
        recv_blacklist_lock_r = 0x30FB,
        recv_blacklist_open_r = 0xDF31,
        recv_blacklist_unlock_r = 0x2BAB,
        recv_blacklist_update = 0xA63A,
        recv_buff_request_detach_r = 0xC96F,
        recv_buff_shop_buy_r = 0x8325,
        recv_buff_shop_notify_item = 0xB24C,
        recv_buff_shop_notify_open = 0x14F6,
        recv_cash_shop2_buy_r = 0x9E19,
        recv_cash_shop2_notify_item = 0xC3EE,
        recv_cash_shop2_notify_open = 0x6554,
        recv_cash_shop_buy_r = 0x2D6D,
        recv_cash_shop_check_billing_zip_r = 0x9D5A,
        recv_cash_shop_fitting_begin = 0xDBF1,
        recv_cash_shop_fitting_end = 0xDEB7,
        recv_cash_shop_fitting_equip_r = 0xD0D,
        recv_cash_shop_fitting_item_update_eqmask = 0xFCAD,
        recv_cash_shop_fitting_unequip_r = 0x1C20,
        recv_cash_shop_get_current_cash_r = 0xA005,
        recv_cash_shop_get_url_commerce_r = 0x1D49,
        recv_cash_shop_get_url_common_r = 0x1A6,
        recv_cash_shop_get_url_common_steam_r = 0xA18D,
        recv_cash_shop_get_url_r = 0x7F09,
        recv_cash_shop_get_url_web_goods_r = 0x570B,
        recv_cash_shop_notify_item = 0xD597,
        recv_cash_shop_notify_open = 0x732D,
        recv_cash_shop_open_by_menu = 0x0,//missing recv
        recv_cash_shop_regist_billing_zip_r = 0x7A6F,
        recv_channel_notify = 0x2849,
        recv_chara_move_speed_per = 0xCCE2,
        recv_chara_notify_map_fragment = 0xA7E8,
        recv_chara_notify_party_join = 0x58A8,
        recv_chara_notify_party_leave = 0x9F70,
        recv_chara_notify_raise_downper = 0xBCC2,
        recv_chara_notify_stateflag = 0x23D3,
        recv_chara_notify_union_data = 0xA0E3,
        recv_chara_pose_ladder_r = 0xD972,
        recv_chara_pose_notify = 0xB6B1,
        recv_chara_pose_r = 0xF71C,
        recv_chara_target_move_side_speed_per = 0x5DB7,
        recv_chara_update_ability = 0xCBA2,
        recv_chara_update_battle_base_param = 0x2F2F,
        recv_chara_update_ac = 0x2BA4,
        recv_chara_update_action_prohibit = 0x5F6C,
        recv_chara_update_action_prohibit_camp = 0xC24E,
        recv_chara_update_alignment = 0xEF9,
        recv_chara_update_alignment_param = 0xB435,
        recv_chara_update_ap = 0x6A7A,
        recv_chara_update_ap_cost_diff = 0x7A5C,
        recv_chara_update_ap_cost_per = 0x661,
        recv_chara_update_atk_magic_attr = 0xD0BB,
        recv_chara_update_con = 0x28E7,
        recv_chara_update_condition_resist = 0x780,
        recv_chara_update_def_magic_attr = 0xC067,
        recv_chara_update_form = 0x2479,
        recv_chara_update_hp = 0xD133,
        recv_chara_update_job_attr_mp_cost_per = 0x322F,
        recv_chara_update_job_attr_skill_cooltime_per = 0xEFE3,
        recv_chara_update_lv = 0xB102,
        recv_chara_update_lv_detail = 0xA9C2,
        recv_chara_update_lv_detail2 = 0xD5B5,
        recv_chara_update_lv_detail_end = 0x2CB0,
        recv_chara_update_lv_detail_start = 0x4E10,
        recv_chara_update_mag_cast_time_per = 0xFD78,
        recv_chara_update_mag_mp_cost_per = 0x2AB0,
        recv_chara_update_maxac = 0x65A6,
        recv_chara_update_maxap = 0x2478,
        recv_chara_update_maxhp = 0x9F31,
        recv_chara_update_maxmp = 0x6B74,
        recv_chara_update_maxweight = 0xA873,
        recv_chara_update_mp = 0x2576,
        recv_chara_update_notify_comment = 0x8072,
        recv_chara_update_notify_crime_lv = 0xAF7F,
        recv_chara_update_notify_honor = 0x8C2F,
        recv_chara_update_notify_item_forth = 0xB631,
        recv_chara_update_notify_rookie = 0xC1DC,
        recv_chara_update_weight = 0x3223,
        recv_chara_view_landing_notify = 0x14DA,
        recv_charabody_access_end = 0x89FF,
        recv_charabody_access_start_r = 0xEFED,
        recv_charabody_loot_complete2_r = 0x54E,
        recv_charabody_loot_start2_r = 0xB2F,
        recv_charabody_notify_crime_lv = 0xB3DA,
        recv_charabody_notify_deadstate = 0xCC36,
        recv_charabody_notify_loot_item = 0x8CDE,
        recv_charabody_notify_loot_start2 = 0xFFD2,
        recv_charabody_notify_loot_start_cancel = 0x2FA,
        recv_charabody_notify_party_join = 0xD67D,
        recv_charabody_notify_party_leave = 0x5A5,
        recv_charabody_notify_spirit = 0x36A6,
        recv_charabody_salvage_end = 0xD688,
        recv_charabody_salvage_notify_body = 0x7D1C,
        recv_charabody_salvage_notify_salvager = 0xA8A0,
        recv_charabody_salvage_request_cancel_r = 0x9578,
        recv_charabody_salvage_request_r = 0x2257,
        recv_charabody_self_notify_abyss_stead_pos = 0x679B,
        recv_charabody_self_notify_deadnext_time = 0xB417,
        recv_charabody_self_raisescale_end = 0xC22F,
        recv_charabody_self_salvage_end = 0x12E0,
        recv_charabody_self_salvage_notify = 0x12A4,
        recv_charabody_self_salvage_request_cancel = 0xDB88,
        recv_charabody_self_salvage_result = 0x3E7F,
        recv_charabody_self_warpdragon_penalty = 0x1E65,
        recv_charabody_state_update_notify = 0x1A0F,
        recv_chat_notify_message = 0xC003,
        recv_chat_post_message_r = 0xAF49,
        recv_check_job_change_r = 0x8F15,
        recv_cloak_close_r = 0xF330,
        recv_cloak_notify_close_r = 0x723,
        recv_cloak_notify_open = 0xFED8,
        recv_cmd_exec_r = 0x6F32,
        recv_comment_set_r = 0x9C3A,
        recv_comment_switch_r = 0xB025,
        recv_cpf_authenticate = 0xBA73,
        recv_cpf_notify_error = 0x73D7,
        recv_create_package_r = 0x5A5F,
        recv_create_send_pacakge_info = 0x2491,
        recv_data_get_self_chara_data_r = 0xD1BD,
        recv_data_get_self_chara_data_request_r = 0x3C89,
        recv_data_notify_chara_data = 0xED4C,
        recv_data_notify_charabody_data = 0x906A,
        recv_data_notify_debug_object_data = 0x6510,
        recv_data_notify_eo_data = 0x8075,
        recv_data_notify_eo_data2 = 0xEDB3,
        recv_data_notify_eventlink = 0xB813,
        recv_data_notify_ggate_stone_data = 0x250E,
        recv_data_notify_gimmick_data = 0xBFE9,
        recv_data_notify_goldobject_data = 0xE051,
        recv_data_notify_itemobject_data = 0xCFDC,
        recv_data_notify_maplink = 0x7D25,
        recv_data_notify_monster_data = 0xFDB8,
        recv_data_notify_npc_data = 0x2470,
        recv_data_notify_npc_ex_dragon = 0x6C79,
        recv_data_notify_soulmaterialobject_data = 0x201C,
        recv_dbg_battle_charge_end_notify = 0xA84F,
        recv_dbg_battle_charge_start_notify = 0xCF2B,
        recv_dbg_battle_guard_end_notify = 0x170B,
        recv_dbg_battle_guard_start_notify = 0xB0BF,
        recv_dbg_chara_equipped = 0x3D6C,
        recv_dbg_chara_unequipped = 0xEA1C,
        recv_dbg_message = 0x9DE2,
        recv_dbg_option_change_r = 0xC5F,
        recv_dbg_select_raise_r = 0xCD63,
        recv_door_close_r = 0x772A,
        recv_door_open_r = 0x5842,
        recv_door_update_notify = 0x9870,
        recv_dropobject_notify_access_priority = 0x10C5,
        recv_dropobject_notify_stateflag = 0x965E,
        recv_echo_notify = 0x8F84,
        recv_echo_r = 0xCF52,
        recv_emotion_notify_type = 0xF95B,
        recv_emotion_update_type_r = 0x239D,
        recv_eo_base_notify_sphere = 0xAF6D,
        recv_eo_notify_disappear_schedule = 0xC177,
        recv_eo_update_end_trapid = 0xE8BF,
        recv_eo_update_second_trapid = 0x96EA,
        recv_eo_update_state = 0x28FD,
        recv_equip_honor_r = 0x92DE,
        recv_escape_cancel = 0x8CC6,
        recv_escape_exec = 0xD0B7,
        recv_escape_start = 0xD68C,
        recv_event_abort_r = 0x79A2,
        recv_event_access_object_r = 0x77A7,
        recv_event_block_message = 0x8BD2,
        recv_event_block_message_end_no_object = 0x1AB,
        recv_event_block_message_no_object = 0x8D9B,
        recv_event_change_cancel_sw = 0x7D53,
        recv_event_change_type = 0x32ED,
        recv_event_end = 0x99D,
        recv_event_message = 0x662F,
        recv_event_message_no_object = 0xCC37,
        recv_event_quest_order = 0x267B,
        recv_event_quest_order_list_begin = 0x5CF8,
        recv_event_quest_report = 0xE07E,
        recv_event_quest_report_list_begin = 0x7004,
        recv_event_quest_report_list_begin2 = 0xFDE9,
        recv_event_removetrap_begin = 0xB292,
        recv_event_removetrap_trap_start = 0x000, // opcode not found
        recv_event_removetrap_close = 0xA643,
        recv_event_removetrap_ident_trap_update = 0xB0E5,
        recv_event_removetrap_release_rate_close = 0xDCB6,
        recv_event_removetrap_release_rate_update = 0x26B8,
        recv_event_removetrap_select_r = 0xFEB7,
        recv_event_removetrap_skill_r2 = 0xD400,
        recv_event_request_int = 0xB782,
        recv_event_script_play = 0x8091,
        recv_event_select_channel = 0x4992,
        recv_event_select_exec = 0x6A56,
        recv_event_select_exec_winpos = 0x4404,
        recv_event_select_map_and_channel = 0xCF24,
        recv_event_select_push = 0x32F7,
        recv_event_select_ready = 0xE1F8,
        recv_event_show_board_end = 0x125E,
        recv_event_show_board_start = 0x5EDB,
        recv_event_soul_rankup_open = 0x394F,
        recv_event_soul_storage_open = 0x3DD0,
        recv_event_start = 0x1B5C,
        recv_event_sync = 0x462E,
        recv_event_system_message = 0x561,
        recv_event_system_message_timer = 0xAE27,
        recv_event_system_message_timer_end = 0x5016,
        recv_event_tresurebox_begin = 0xBD7E,
        recv_event_tresurebox_select_r = 0x494,
        recv_event_union_storage_close_r = 0xBB65,
        recv_event_union_storage_open = 0x1105,
        recv_event_union_storage_update_money = 0x7D21,
        recv_forge_check_r = 0x90E8,
        recv_forge_execute_r = 0xAD6D,
        recv_forge_notify_execute_result = 0x88A1,
        recv_forge_sp_check_r = 0x5D52,
        recv_forge_sp_execute_r = 0x7341,
        recv_gamepot_web_close_r = 0x213C,
        recv_gamepot_web_notify_open = 0xBA89,
        recv_gem_break_cost_r = 0x42DE,
        recv_gem_break_r = 0x6912,
        recv_gem_cancel_piece_r = 0x6DB4,
        recv_gem_cancel_support_item_r = 0x1FEE,
        recv_gem_cancel_synthesis_r = 0x65DD,
        recv_gem_close_r = 0xABF2, // after sends - send_stall_set_name
        recv_gem_notify_close = 0x18CC,
        recv_gem_notify_open = 0xC206,
        recv_gem_rebuild_info = 0x36DC,
        recv_gem_rebuild_r = 0x935B,
        recv_gem_set_piece_r = 0xD6A4,
        recv_gem_set_r = 0x32CD,
        recv_gem_set_support_item_r = 0x9D52,
        recv_gem_set_synthesis_r = 0x316F,
        recv_gem_synthesis_info = 0x9F5,
        recv_gem_synthesis_r = 0x4E7B,
        recv_get_honor = 0xBD72,
        recv_get_honor_notify = 0xA54C,
        recv_get_recv_package = 0x9D96,
        recv_get_refusallist_r = 0x488E,
        recv_get_send_package = 0x30BE,
        recv_get_thread_all_r = 0xBFEA,
        recv_get_thread_record_r = 0x6547,
        recv_gimmick_access_object_notify = 0xD804,
        recv_gimmick_access_object_r = 0xA4A5,
        recv_gimmick_state_update = 0x1041,
        recv_help_new_add = 0xFF3F,
        recv_help_new_data = 0x3C41,
        recv_help_new_remove_r = 0xC0D8,
        recv_inherit_start_r = 0xF3A1,
        recv_item_cooltime_notify = 0xECF,
        recv_item_drop_r = 0xBFE,
        recv_item_equip_r = 0x551E,
        recv_item_instance = 0x86EA,
        recv_item_instance_unidentified = 0xD57A,
        recv_item_move_r = 0x708B,
        recv_item_remove = 0x9700,
        recv_item_sort_r = 0x4D70,
        recv_item_unequip_r = 0x9A79,
        recv_item_update_ac = 0x1C15,
        recv_item_update_date_end_protect = 0x2063,
        recv_item_update_durability = 0x1F5A,
        recv_item_update_enchantid = 0x9B08,
        recv_item_update_eqmask = 0x3BD3,
        recv_item_update_hardness = 0x2C5,
        recv_item_update_level = 0x2CAF,
        recv_item_update_magic = 0x992,
        recv_item_update_maxdur = 0x443C,
        recv_item_update_num = 0x5F8,
        recv_item_update_physics = 0xA611,
        recv_item_update_place = 0xB371,
        recv_item_update_place_change = 0xD6A8,
        recv_item_update_sp_level = 0xC7E1,
        recv_item_update_spirit_eqmask = 0xE819,
        recv_item_update_state = 0x3247,
        recv_item_update_weight = 0x848B,
        recv_item_use_notify = 0x75A5,
        recv_item_use_r = 0x2BBF,
        recv_job_change_close_r = 0xFC1A,
        recv_job_change_notify_close = 0xE45,
        recv_job_change_notify_exe = 0x88AE,
        recv_job_change_notify_open = 0x1FE4,
        recv_job_change_param = 0xAB14,
        recv_job_change_r = 0xA21E,
        recv_job_change_select_bonuspoint_r = 0x1837,
        recv_logout_cancel = 0x1198,
        recv_logout_cancel_request_r = 0x267D,
        recv_logout_start = 0x58E7,
        recv_logout_start_request_r = 0x4C8B,
        recv_loot_access_object_r = 0x6023,
        recv_mail_open_r = 0xCE7,
        recv_map_change_force = 0x4C74,
        recv_map_change_sync_ok = 0x9AA9,
        recv_map_enter_r = 0x793E,
        recv_map_entry_r = 0xF9F9,
        recv_map_fragment_flag = 0xD349,
        recv_map_get_info_r = 0xEDA6,
        recv_map_update_bgm = 0xE14B,
        recv_message_board_close_r = 0x6001,
        recv_message_board_notify_close = 0xCBBD,
        recv_message_board_notify_open = 0x170F,
        recv_message_board_notify_update = 0x9227,
        recv_minimap_notify = 0xE0D5,
        recv_monster_hate_off = 0xBC0A,
        recv_monster_hate_on = 0x5C47,
        recv_monster_state_update_notify = 0x5527,
        recv_normal_system_message = 0xAE2B,
        recv_npc_affection_rank_update_notify = 0xF6AF,
        recv_npc_flageffect_update_notify = 0x560,
        recv_npc_ggate_state_update_notify = 0x3544,
        recv_npc_state_update_notify = 0x3B77,
        recv_object_ac_rank_update_notify = 0x5243,
        recv_object_disappear_notify = 0x717D,
        recv_object_hp_per_update_notify = 0xFF00,
        recv_object_point_move_notify = 0xEEF0,
        recv_object_point_move_r = 0x7B5D,
        recv_object_region_break_update_notify = 0x1052,
        recv_object_region_disappear_update_notify = 0xCF2A,
        recv_object_sub_target_update_notify = 0x23E5,
        recv_package_all_delete_r = 0xFDB2,
        recv_package_notify_add = 0x556E,
        recv_party_accept_to_apply_r = 0xCFF,
        recv_party_accept_to_invite_r = 0x32AE,
        recv_party_apply_r = 0x5F1A,
        recv_party_cancel_member_recruit_r = 0xB0FC,
        recv_party_cancel_party_recruit_r = 0xA4D3,
        recv_party_change_leader_r = 0x7BB3,
        recv_party_change_mode_r = 0x3428,
        recv_party_decline_to_apply_r = 0x855C,
        recv_party_decline_to_invite_r = 0x6175,
        recv_party_disband_r = 0x6979,
        recv_party_entry_draw_r = 0x85EA,
        recv_party_establish_r = 0x4DF8,
        recv_party_invite_r = 0x300A,
        recv_party_kick_r = 0xE207,
        recv_party_leave_r = 0xFE2F,
        recv_party_notify_add_draw_item = 0xE748,
        recv_party_notify_cancel_member_recruit = 0x5393,
        recv_party_notify_cancel_party_recruit = 0x839A,
        recv_party_notify_failed_draw = 0xCB6D,
        recv_party_notify_failed_draw_all = 0x68AA,
        recv_party_notify_get_item = 0xF7F0,
        recv_party_notify_recruit_request = 0x9F8F,
        recv_party_notify_remove_draw_item = 0x7576,
        recv_party_regist_member_recruit_r = 0xA7BF,
        recv_party_search_recruited_member_r = 0xF495,
        recv_party_search_recruited_party_r = 0xA45C,
        recv_premium_service_notify_attach = 0x3B1,
        recv_premium_service_notify_attach2 = 0x8299,
        recv_premium_service_notify_detach = 0x2C30,
        recv_premium_service_update_day = 0xE03D,
        recv_premium_service_update_time = 0xFD54,
        recv_quest_abort_r = 0x6D46,
        recv_quest_chapter_target_updated = 0x6C7B,
        recv_quest_chapter_updated = 0xC119,
        recv_quest_check_target_r = 0xBCAB,
        recv_quest_check_time_limit_r = 0xC2E9,
        recv_quest_display_r = 0x42B8,
        recv_quest_ended = 0xB02C,
        recv_quest_get_mission_quest_history = 0x0,//missing recv?
        recv_quest_get_mission_quest_works_r = 0x1BD6,
        recv_quest_get_soul_mission_quest_history = 0x0,//missing recv?
        recv_quest_get_soul_mission_quest_works_r = 0x266C,
        recv_quest_get_story_quest_history = 0x0,//missing recv?
        recv_quest_get_story_quest_works_r = 0x73A1,
        recv_quest_hint = 0x505E,
        recv_quest_hint_othermap = 0xFFD6,
        recv_quest_hint_remove = 0x63B2,
        recv_quest_history = 0x32FF,
        recv_quest_select_error = 0xE5FF,
        recv_quest_started = 0xD46E,
        recv_quest_target_count_r = 0x465C,
        recv_raisescale_add_item_r = 0xF602,
        recv_raisescale_move_money_r = 0x98D3,
        recv_raisescale_open_cash_shop_r = 0x6030,
        recv_raisescale_remove_item_r = 0xEF8D,
        recv_raisescale_request_revive_r = 0xA0FA,
        recv_raisescale_update_success_per = 0xA508,
        recv_raisescale_view_close = 0x260E,
        recv_raisescale_view_open = 0xC25D,
        recv_random_box_close_r = 0x924E,
        recv_random_box_get_item_all_r = 0xF02B,
        recv_random_box_get_item_r = 0xC444,
        recv_random_box_next_open_r = 0xD1A9,
        recv_random_box_notify_open = 0xC374,
        recv_record_close_r = 0xE0B,
        recv_record_notify_open = 0x2353,
        recv_record_notify_param = 0x951B,
        recv_refusallist_add_user_r = 0x22E7,
        recv_refusallist_remove_user_r = 0x9A44,
        recv_return_home_request_exec_r = 0xFCC0,
        recv_revive_init_r = 0xEF4E,
        recv_revive_execute_r = 0x621A,
        recv_select_package_update_r = 0xD170,
        recv_self_action_cost = 0x8CD,
        recv_self_buff_notify = 0x73D1,
        recv_self_dragon_warp_notify = 0xC6EF,
        recv_self_exp_notify = 0xC47A,
        recv_self_inherit_skill_level_notify = 0x3F5B,
        recv_self_lost_notify = 0x789E,
        recv_self_money_notify = 0xA146,
        recv_self_returnhome_interval = 0xC300,
        recv_self_skill_point_notify = 0x3B9F,
        recv_self_soul_material_notify = 0x9CCF,
        recv_self_soul_point_notify = 0x182B,
        recv_self_soul_rank_notify = 0x9E75,
        recv_self_soul_toggle_ability_notify = 0xD43F,
        recv_self_toggle_ability_notify = 0x4B94,
        recv_shop_buy_r = 0x2467,
        recv_shop_close_r = 0x4E5C,
        recv_shop_identify_r = 0xECBA,
        recv_shop_message_init = 0xE7C0,
        recv_shop_message_push = 0x15D0,
        recv_shop_notify_close = 0x61C8,
        recv_shop_notify_item = 0xF447,
        recv_shop_notify_item_sell_price = 0xE039,
        recv_shop_notify_open = 0x52FD,
        recv_shop_notify_sell_surrogate_fee = 0xDE90,
        recv_shop_repair_r = 0x29AF,
        recv_shop_sell_check_r = 0x4E8D,
        recv_shop_sell_r = 0xD4F8,
        recv_shop_title_push = 0xDEC2,
        recv_shortcut_notify_deregist = 0x1F73,
        recv_shortcut_notify_regist = 0x8BB4,
        recv_shortcut_request_data_r = 0xA084,
        recv_shortcut_request_deregist_r = 0x42B6,
        recv_shortcut_request_regist_r = 0x27D6,
        recv_situation_end = 0x124C,
        recv_situation_start = 0x1AA8,
        recv_sixthsense_trap_notify = 0xBA11,
        recv_skill_aptitude_gain = 0x6911,
        recv_skill_aptitude_lost = 0xC0BB,
        recv_skill_base_notify = 0x1392,
        recv_skill_cast_cancel = 0xD55D,
        recv_skill_combo_cast_r = 0xC543,
        recv_skill_cooltime_notify = 0xA6F8,
        recv_skill_custom_close_r = 0x411,
        recv_skill_custom_notify_close = 0xA548,
        recv_skill_custom_notify_open = 0xB319,
        recv_skill_custom_slot_set_r = 0x7F34,
        recv_skill_exec_r = 0x1C6C,
        recv_skill_inherit_lost = 0x11FA,
        recv_skill_next_cast_r = 0x7F50,
        recv_skill_request_base_from_item_r = 0xA520,
        recv_skill_request_gain_r = 0x903A,
        recv_skill_start_cast_ex_r = 0x4C6F,
        recv_skill_start_cast_r = 0xE4B2,
        recv_skill_start_cast_self = 0xC542,
        recv_skill_start_item_cast_r = 0xEE43,
        recv_skill_tree_gain = 0x8395,
        recv_skill_tree_lost = 0x2A3F,
        recv_skill_tree_notify = 0x1C0A,
        recv_soul_dispitem_notify_data = 0x15B0,
        recv_soul_dispitem_remove_data = 0x70F6,
        recv_soul_dispitem_request_data_r = 0xD5FD,
        recv_souleater_touch_notify = 0x1F32,
        recv_soulmaterial_shop_buy_r = 0x86A5,
        recv_soulmaterial_shop_notify_item = 0x808B,
        recv_soulmaterial_shop_notify_open = 0x2631,
        recv_stall_buy_item_r = 0x5E79,
        recv_stall_close_r = 0x397,
        recv_stall_deregist_item_r = 0x196E,
        recv_stall_notify_closed = 0x2FFF,
        recv_stall_notify_opend = 0x7FC5,
        recv_stall_open_r = 0x9761,
        recv_stall_regist_item_r = 0x9289,
        recv_stall_sell_item = 0x919C,
        recv_stall_set_item_price_r = 0x2DCE,
        recv_stall_set_name_r = 0xB212,
        recv_stall_shopping_abort_r = 0x70B7,
        recv_stall_shopping_notify_aborted = 0x8661,
        recv_stall_shopping_start_r = 0xA2B7,
        recv_stall_update_feature_item = 0xB195,
        recv_storage_deposit_item2_r = 0xC8AD,
        recv_storage_deposit_money_r = 0x6539,
        recv_storage_draw_item2_r = 0xD43D,
        recv_storage_drawmoney = 0x79A9,
        recv_sv_conf_option_change = 0xAEE9,
        recv_sv_conf_option_change_r = 0xAEE9,
        recv_sv_conf_option_request_r = 0x1DA,
        recv_talkring_create_masterring_r = 0xCAB1,
        recv_talkring_rename_masterring_r = 0xBBA5,
        recv_talkring_rename_request = 0xAADD,
        recv_temple_close_r = 0x3B6,
        recv_temple_cure_curse_r = 0x850B,
        recv_temple_notify_close = 0xA43B,
        recv_temple_notify_open = 0x85C6,
        recv_thread_create_r = 0xAA8F,
        recv_thread_enter_r = 0x692B,
        recv_thread_entry_message = 0x8D74,
        recv_thread_exit_message = 0x95E6,
        recv_thread_exit_r = 0x2F0E,
        recv_trade_abort_r = 0x88FB,
        recv_trade_add_item_r = 0x52C9,
        recv_trade_fix_r = 0x8A06,
        recv_trade_invite_r = 0xEFA4,
        recv_trade_notify_aborted = 0xB619,
        recv_trade_notify_fixed = 0x62E2,
        recv_trade_notify_interface_status = 0xCB94,
        recv_trade_notify_invited = 0x1D68,
        recv_trade_notify_money = 0xBF34,
        recv_trade_notify_offerd = 0x5C15,
        recv_trade_notify_problem = 0x3E0B,
        recv_trade_notify_replied = 0x102E,
        recv_trade_notify_reverted = 0x536A,
        recv_trade_remove_item_r = 0x715E,
        recv_trade_reply_r = 0x8DBC,
        recv_trade_revert_r = 0xEDB9,
        recv_trade_set_money_r = 0x971B,
        recv_union_close_window_r = 0x2246,
        recv_union_mantle_close_r = 0x65C,
        recv_union_mantle_open = 0xE0A6,
        recv_union_open_window = 0x7D75,
        recv_union_rename_close_r = 0xE7E7,
        recv_union_rename_open = 0x442A,
        recv_union_request_disband_result = 0xB10F,
        recv_union_request_establish_r = 0x1701,
        recv_union_request_growth_result = 0x3C68,
        recv_union_request_mantle_get_result = 0x50B2,
        recv_union_request_rename_r = 0xE462,
        recv_union_request_secede_result = 0x60E5,
        recv_union_storage_deposit_money_r = 0x8778,
        recv_union_storage_draw_money_r = 0x4440,
        recv_union_storage_move_item_r = 0x2790,
        recv_wanted_entry_r = 0xDDD3,
        recv_wanted_jail_close_r = 0x7442,
        recv_wanted_jail_draw_point_r = 0xC54F,
        recv_wanted_jail_open = 0xE7BB,
        recv_wanted_jail_payment_r = 0x4537,
        recv_wanted_jail_update_draw_point = 0xD6F0,
        recv_wanted_jail_update_money = 0x794,
        recv_wanted_jail_update_state = 0xC68B,
        recv_wanted_list_actor = 0x7CF0,
        recv_wanted_list_close_r = 0xC1AF,
        recv_wanted_list_member = 0xEB7B,
        recv_wanted_list_open = 0xC6F2,
        recv_wanted_update_reward_point = 0xFCF3,
        recv_wanted_update_state = 0xDD52,
        recv_wanted_update_state_actor_notify = 0xAFD1,
        recv_wanted_update_state_notify = 0x66EC,
        

        // Send OP Codes - ordered by op code

        send_auction_bid = 0x63BC, 
        send_auction_cancel_bid = 0xBC65,
        send_auction_cancel_exhibit = 0x375B,
        send_auction_close = 0xE732,
        send_auction_exhibit = 0xED52, 
        send_auction_re_exhibit = 0x33, //opcode not found
        send_auction_receive_gold = 0x34, //opcode not found
        send_auction_receive_item = 0x35, //opcode not found
        send_auction_search = 0x8865, 
        send_base_check_version = 0x5705, 
        send_base_enter = 0xAE43, 
        send_battle_attack_exec = 0xC38D, 
        send_battle_attack_exec_direct = 0x37, //opcode not found   TODO
        send_battle_attack_next = 0x9D74, 
        send_battle_attack_pose = 0xC137, 
        send_movement_info = 0x6A72, // this is a custom string 
        send_battle_attack_start = 0x3B2D,
        send_battle_charge_end = 0x39, //opcode not found   TODO
        send_battle_charge_start = 0x40, //opcode not found   TODO
        send_battle_guard_end = 0xD2E7, 
        send_battle_guard_start = 0x4362, 
        send_battle_release_attack_pose = 0x26BE, 
        send_blacklist_clear = 0xB742, 
        send_blacklist_close = 0xC780, 
        send_blacklist_lock = 0xD189, 
        send_blacklist_open = 0xC923, 
        send_blacklist_unlock = 0x23AD, 
        send_buff_request_detach = 0x43, //opcode not found
        send_buff_shop_buy = 0x44, //opcode not found   TODO
        send_cash_shop2_buy = 0x45, //opcode not found
        send_cash_shop_buy = 0x46, //opcode not found  TODO
        send_cash_shop_check_billing_zip = 0x47, //opcode not found
        send_cash_shop_fitting_equip = 0x48, //opcode not found
        send_cash_shop_fitting_unequip = 0x49, //opcode not found
        send_cash_shop_get_current_cash = 0x50, //opcode not found
        send_cash_shop_get_url_common = 0x51, //opcode not found
        send_cash_shop_get_url_common_steam = 0x52, //opcode not found
        send_cash_shop_open_by_menu = 0x9945, 
        send_cash_shop_regist_billing_zip = 0x53, //opcode not found
        send_character_view_offset = 0xE4AE, //this is not a real send, it is only for getting the view offset for the character movement
        send_chara_pose = 0x7DE7, 
        send_chara_pose_ladder = 0xE75C, 
        send_chara_view_landing = 0x54, //opcode not found   //TODO
        send_charabody_access_abort = 0x55, //opcode not found
        send_charabody_access_start = 0x6D2F, 
        send_charabody_loot_complete2 = 0x56, //opcode not found
        send_charabody_loot_complete3 = 0x57, //opcode not found 
        send_charabody_loot_start2 = 0x58, //opcode not found
        send_charabody_loot_start2_cancel = 0x59, //opcode not found
        send_charabody_loot_start3 = 0x61, //opcode not found
        send_charabody_salvage_abort = 0x6FFC,
        send_charabody_salvage_request = 0x62, //opcode not found // TODO
        send_charabody_salvage_request_cancel = 0x63, //opcode not found
        send_charabody_self_salvage_abort = 0x64, //opcode not found
        send_charabody_self_salvage_notify_r = 0xAAF9,
        send_chat_post_message = 0x1132, 
        send_check_job_change = 0x66,//opcode not found 
        send_cmd_exec = 0x2E64, 
        send_comment_set = 0x9A13, 
        send_comment_switch = 0xECF5, 
        send_create_package = 0xF6D,
        send_data_get_self_chara_data_request = 0x74DD, 
        send_dbg_select_raise = 0x68, //opcode not found
        send_door_close = 0xC218,
        send_door_open = 0x1D8A,
        send_emotion_update_type = 0x7672, 
        send_equip_honor = 0x70, //opcode not found  TODO
        send_event_abort = 0x71, //opcode not found  TODO
        send_event_access_object = 0x718D, 
        send_event_quest_get_order_list = 0x72, //opcode not found
        send_event_quest_order_list_end = 0x73, //opcode not found
        send_event_quest_order_r = 0x86A9,
        send_event_quest_order_select = 0x75, //opcode not found 
        send_event_quest_report_list_end = 0x76, //opcode not found
        send_event_quest_report_r = 0x77, //opcode not found
        send_event_quest_report_select = 0x78, //opcode not found
        send_event_removetrap_end = 0x87CD,
        send_event_removetrap_select = 0x4CE9,
        send_event_removetrap_skill = 0x81, //opcode not found  TODO
        send_event_request_int_r = 0x60, 
        send_event_script_play_r = 0xA3B5,
        send_event_select_channel_r = 0x1C22,
        send_event_select_exec_r = 0x6439,
        send_event_select_map_and_channel_r = 0xB87F, //opcode not found
        send_event_soul_rankup_close = 0x4D03,
        send_event_soul_storage_close = 0x26D2,
        send_event_sync_r = 0x701D,
        send_event_system_message_timer_r = 0x90, //opcode not found
        send_event_tresurebox_end = 0x5F7A,
        send_event_tresurebox_select = 0x92, //opcode not found   TODO
        send_event_union_storage_close = 0x93, //opcode not found
        send_forge_check = 0x94, //opcode not found
        send_forge_execute = 0x95, //opcode not found
        send_forge_sp_check = 0x96, //opcode not found
        send_forge_sp_execute = 0x97, //opcode not found
        send_gamepot_web_close = 0x98, //opcode not found
        send_gem_break = 0x99, //opcode not found
        send_gem_break_cost = 0x100, //opcode not found
        send_gem_cancel_piece = 0x101, //opcode not found
        send_gem_cancel_support_item = 0x102, //opcode not found
        send_gem_cancel_synthesis = 0x103, //opcode not found
        send_gem_close = 0x483D,
        send_gem_rebuild = 0x105, //opcode not found
        send_gem_set = 0x106, //opcode not found
        send_gem_set_piece = 0x107, //opcode not found
        send_gem_set_support_item = 0x108, //opcode not found
        send_gem_set_synthesis = 0x109, //opcode not found
        send_gem_synthesis = 0x110, //opcode not found
        send_get_refusallist = 0x6C17, 
        send_gimmick_access_object = 0xCAD8, 
        send_help_new_remove = 0x12E7,
        send_inherit_start = 0x113, //opcode not found
        send_item_drop = 0xBE26,
        send_item_equip = 0x279F,
        send_item_move = 0x8C7C,
        send_item_sort = 0x4926,
        send_item_unequip = 0xA3DE,
        send_item_use_item = 0x119, //opcode not found
        send_item_use_object = 0x120, //opcode not found
        send_job_change = 0x121, //opcode not found
        send_job_change_close = 0x122, //opcode not found   TODO
        send_job_change_select_bonuspoint = 0x123, //opcode not found
        send_logout_cancel_request = 0xB224, 
        send_logout_start_request = 0x38FC, 
        send_loot_access_object = 0xB776,
        send_map_change_force_r = 0x4CB0, 
        send_map_enter = 0x70FD, 
        send_map_entry = 0x2DE3, 
        send_map_get_info = 0x25D7, 
        send_message_board_close = 0x125, //opcode not found   // TODO
        send_open_mailbox = 0xEF32,
        send_package_all_delete = 0x8E0C,
        send_party_accept_to_apply = 0x127, //opcode not found
        send_party_accept_to_invite = 0x19E3,
        send_party_apply = 0x534F, 
        send_party_cancel_member_recruit = 0x130, //opcode not found
        send_party_cancel_party_recruit = 0x131, //opcode not found
        send_party_change_leader = 0x132, //opcode not found
        send_party_change_mode = 0x133, //opcode not found
        send_party_decline_to_apply = 0x134, //opcode not found
        send_party_decline_to_invite = 0x738C,
        send_party_disband = 0x136,//opcode not found
        send_party_entry_draw = 0x137, //opcode not found
        send_party_establish = 0xAF25,
        send_party_establish_2 = 0x139, //opcode not found
        send_party_establish_3 = 0x140, //opcode not found
        send_party_establish_4 = 0x226, //opcode not found
        send_party_establish_5 = 0x227, //opcode not found
        send_party_establish_6 = 0x228, //opcode not found
        send_party_establish_7 = 0x229, //opcode not found
        send_party_invite = 0x9471,
        send_party_invite_2 = 0x142, //opcode not found
        send_party_invite_3 = 0x143, //opcode not found
        send_party_kick = 0x144, //opcode not found
        send_party_leave = 0x5F80,
        send_party_pass_draw = 0x146, //opcode not found
        send_party_regist_member_recruit = 0xC342, //opcode not found
        send_party_regist_party_recruit = 0x7B6C, //opcode not found
        send_party_request_draw_item_list = 0x86FD, 
        send_party_search_recruited_member = 0xCB62, 
        send_party_search_recruited_party = 0x90BD, 
        send_quest_abort = 0xD247,
        send_quest_check_target = 0x1E86,
        send_quest_check_time_limit = 0x152, //opcode not found
        send_quest_display = 0x3017, 
        send_quest_get_mission_quest_history = 0xA3E6, 
        send_quest_get_mission_quest_works = 0x7C9A, 
        send_quest_get_soul_mission_quest_history = 0x9E5C, 
        send_quest_get_soul_mission_quest_works = 0xB090, 
        send_quest_get_story_quest_history = 0xCB91, 
        send_quest_get_story_quest_works = 0x2A95, 
        send_quest_target_count = 0x154, //opcode not found
        send_raisescale_add_item = 0x155, //opcode not found
        send_raisescale_move_money = 0x156, //opcode not found
        send_raisescale_open_cash_shop = 0x157, //opcode not found
        send_raisescale_remove_item = 0x158, //opcode not found
        send_raisescale_request_revive = 0x159, //opcode not found
        send_raisescale_request_revive_event = 0x160, //opcode not found
        send_raisescale_view_close_request = 0x161, //opcode not found
        send_random_box_close = 0x6ABB,
        send_random_box_get_item = 0x163, //opcode not found  TODO
        send_random_box_get_item_all = 0x164, //opcode not found
        send_random_box_next_open = 0x167, //opcode not found  TODO
        send_record_close = 0x168, //opcode not found
        send_refusallist_add_user = 0xF1D5, 
        send_return_home_request_exec = 0x09F4,
        send_revive_execute = 0x170, //opcode not found TODO
        send_revive_init = 0x171, //opcode not found  TODO
        send_select_package_update = 0x2A64,
        send_shop_buy = 0x173, //opcode not found   TODO
        send_shop_close = 0x2469,
        send_shop_identify = 0x9C7E,
        send_shop_repair = 0xED5C, 
        send_shop_sell = 0xC9F9, 
        send_shop_sell_check = 0xF296 ,
        send_shortcut_request_data = 0x6FC6, 
        send_shortcut_request_deregist = 0x178, //opcode not found
        send_shortcut_request_regist = 0x8090, 
        send_skill_cast_cancel_request = 0x4772,
        send_skill_combo_cast = 0x180, //opcode not found
        send_skill_custom_close = 0x181, //opcode not found
        send_skill_custom_slot_set = 0x182, //opcode not found
        send_skill_exec = 0x2D88,
        send_skill_next_cast = 0x184, //opcode not found
        send_skill_onhit = 0x185, //opcode not found
        send_skill_request_base_from_item = 0x186, //opcode not found
        send_skill_request_gain = 0x6507, 
        send_skill_request_info = 0x4EB5, 
        send_skill_start_cast = 0xF7B9, 
        send_skill_start_item_cast = 0x187, //opcode not found // TODO
        send_soul_dispitem_request_data = 0xEC5A, 
        send_soulmaterial_shop_buy = 0x188, //opcode not found
        send_stall_buy_item = 0x189, //opcode not found
        send_stall_close = 0x957A,
        send_stall_deregist_item = 0xFC7D, 
        send_stall_open = 0x76FC,
        send_stall_regist_item = 0x167E,
        send_stall_set_item_price = 0xDB9F,
        send_stall_set_name = 0xB93, 
        send_stall_shopping_abort = 0x53E3,
        send_stall_shopping_start = 0xB248,
        send_storage_deposit_item = 0x2FA4,
        send_storage_deposit_money = 0xA40B,
        send_storage_draw_item = 0x198, //opcode not found
        send_storage_draw_money = 0xCE05,
        send_sv_conf_option_change = 0x1B99, 
        send_sv_conf_option_request = 0x615E, 
        send_talkring_create_masterring = 0x200, //opcode not found
        send_talkring_rename_masterring = 0x201, //opcode not found
        send_temple_close = 0xEF39,
        send_temple_cure_curse = 0x4A11,
        send_trade_abort = 0x9B38, 
        send_trade_add_item = 0xD060, 
        send_trade_fix = 0x9CC3, 
        send_trade_invite = 0x513A, 
        send_trade_offer = 0xA822,
        send_trade_remove_item = 0x6A8F, 
        send_trade_reply = 0xE9FC,
        send_trade_revert = 0xEC63, 
        send_trade_set_money = 0x7C00,
        send_union_close_window = 0x225A,
        send_union_mantle_close = 0xCF06,
        send_union_rename_close = 0xC9A9, 
        send_union_request_establish = 0x9956,
        send_union_request_rename = 0x217, //opcode not found
        send_union_storage_deposit_money = 0x218, //opcode not found
        send_union_storage_draw_money = 0x219, //opcode not found
        send_union_storage_move_item = 0x220, //opcode not found
        send_update_honor = 0x221, //opcode not found
        send_wanted_entry = 0xA86F, 
        send_wanted_jail_close = 0x86D8, 
        send_wanted_jail_draw_point = 0x309E,
        send_wanted_jail_payment = 0x1C6,
        send_wanted_list_close = 0xABCD,
        
                  
    }
}
